name: "Test"
on:
  pull_request:
  push:
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: Build kaleidogen-web
      uses: cachix/cachix-action@v5
      with:
        name: kaleidogen
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        attributes: kaleidogen-web
  lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: Add static-haskell-nix
      uses: cachix/cachix-action@v5
      with:
        name: static-haskell-nix
        skipNixBuild: true
    - name: Build kaleidogen-lambda
      uses: cachix/cachix-action@v5
      with:
        name: kaleidogen
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        attributes: kaleidogen-lambda
    - name: Build zipfile
      run: |
       nix-build -A function-zip -o function
       cp function/function.zip .
    - name: Deploy to Amazon Lambda
      if: github.ref == 'refs/heads/master'
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: kaleidogen
        zip_file: function.zip
